{
    'name': 'RealTime Product and Loyalty POS sync',
    'version': '16.1.1',
    'description': 'RealTime Product and Loyalty Pos Sync',
    'author': 'Gladdema',
    'website': 'xxx',
    'depends': [
        'base',
        'product',
        'sale_management',
        'purchase',
        'stock',
        'point_of_sale',
        'loyalty',
        'sale_stock',
        'purchase_stock',
    ],
    'data': [
        'security/auth_user_token_security.xml',
        'security/ir.model.access.csv',
        'views/sync_app_config_views.xml',
        'views/auth_user_token_views.xml',
        'views/webhook_log_views.xml',
        'views/auth_user_token_menu.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
    'sequence': 9999,
}